# Generated by Django 3.1.2 on 2020-11-18 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201117_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
