# Generated by Django 3.1.2 on 2020-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201118_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
