# Generated by Django 3.1.4 on 2021-01-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='discussion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discussion'),
        ),
    ]
